openapi: "3.0.0"
info:
  version: 1.0.0
  title: KARA
  license:
    name: MIT
servers:
  - url: kara.rest/api/v1
  - url: bin.dev.zlz.be/api/v1
paths:
  /bins:
    get:
      summary: List all available bins
      parameters:
        - name: page
          in: query
          description: The page to retrieve
          required: false
          schema:
            type: integer
            format: int32
        - name: limit
          in: query
          description: How many items to return at one time (max 100)
          required: false
          schema:
            type: integer
            format: int32
      responses:
        200:
          description: A paged array of bins
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/binList"
    post:
      summary: Create a bin
      responses:
        303:
          description:
          headers:
            link:
              description: link to the new bin
              schema:
                type: string
  /bins/{binId}/logs:
    get:
      summary: retrieves the bin and its requests
      parameters:
        - name: page
          in: query
          description: The page to retrieve
          required: false
          schema:
            type: integer
            format: int32
        - name: limit
          in: query
          description: How many items to return at one time (max 100)
          required: false
          schema:
            type: integer
            format: int32
      responses:
        200:
          description: Bin information and content
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/BinContent"
components:
  schemas:
    Pet:
      required:
        - id
        - name
      properties:
        id:
          type: integer
          format: int64
        name:
          type: string
        tag:
          type: string
    Pets:
      type: array
      items:
        $ref: "#/components/schemas/Pet"
    Error:
      required:
        - code
        - message
      properties:
        code:
          type: integer
          format: int32
        message:
          type: string